In [12]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [13]:
df = pd.read_csv('animals_weight.txt', delim_whitespace=True)

df

C:\Users\arads\AppData\Local\Temp\ipykernel_21188\3706027865.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('animals_weight.txt', delim_whitespace=True)


Brain   Body
0     3.385   44.5
1     0.480   15.5
2     1.350    8.1
3   465.000  423.0
4    36.330  119.5
..      ...    ...
57  160.000  169.0
58    0.900    2.6
59    1.620   11.4
60    0.104    2.5
61    4.235   50.4

[62 rows x 2 columns]

In [14]:
df.isnull().sum()

Brain    0
Body     0
dtype: int64

checking if anyones brain is heavier than their whole body!

In [15]:
df = df.drop(df.index[df.apply(lambda row: row['Brain'] >= row['Body'], axis=1)])

df.reset_index(inplace=True, drop=True)

df

Brain     Body
0      3.385    44.50
1      0.480    15.50
2      1.350     8.10
3     36.330   119.50
4     27.660   115.00
5     14.830    98.20
6      1.040     5.50
7      4.190    58.00
8      0.425     6.40
9      0.101     4.00
10     0.920     5.70
11     1.000     6.60
12     0.005     0.14
13     0.060     1.00
14     3.500    10.80
15     2.000    12.30
16     1.700     6.30
17  2547.000  4603.00
18     0.023     0.30
19   187.100   419.00
20   521.000   655.00
21     0.785     3.50
22    10.000   115.00
23     3.300    25.60
24     0.200     5.00
25     1.410    17.50
26   529.000   680.00
27   207.000   406.00
28    85.000   325.00
29     0.750    12.30
30    62.000  1320.00
31     3.500     3.90
32     6.800   179.00
33    35.000    56.00
34     4.050    17.00
35     0.120     1.00
36     0.023     0.40
37     0.010     0.25
38     1.400    12.50
39   250.000   490.00
40     2.500    12.10
41    55.500   175.00
42   100.000   157.00
43    52.160   440.00
44    10.550   179.50
45     0.550     2.40
46    60.000    81.00
47     3.600    21.00
48     4.288    39.20
49     0.280     1.90
50     0.075     1.20
51     0.122     3.00
52     0.048     0.33
53     3.000    25.00
54   160.000   169.00
55     0.900     2.60
56     1.620    11.40
57     0.104     2.50
58     4.235    50.40

looks like there were some :)

In [16]:
X = df.drop(columns=["Body"])
Y = df["Body"]

In [ ]:
scaler = StandardScaler()
Scaled_X = scaler.fit_transform(X)

Split by 20 percent:

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(Scaled_X, Y, test_size=0.2, random_state=42)

In [19]:
KNN_1 = KNeighborsRegressor(n_neighbors=1)
KNN_3 = KNeighborsRegressor(n_neighbors=3)
KNN_5 = KNeighborsRegressor(n_neighbors=5)
KNN_1.fit(X_train, Y_train)
KNN_3.fit(X_train, Y_train)
KNN_5.fit(X_train, Y_train)

KNeighborsRegressor()

now we predict weight

In [37]:
input = [53.298, 1247.122, 0.583, 0.583, 0.041]

predictions = {
    "KNN_1": [],
    "KNN_3": [],
    "KNN_5": []
}

for value in input:
    scaled_value = scaler.transform(np.array([value]).reshape(1, -1))
    
    predictions["KNN_1"].append(KNN_1.predict(scaled_value)[0])
    predictions["KNN_3"].append(KNN_3.predict(scaled_value)[0])
    predictions["KNN_5"].append(KNN_5.predict(scaled_value)[0])

No1_1 = predictions["KNN_1"]
No3_1 = predictions["KNN_3"]
No5_1 = predictions["KNN_5"]

print(np.float64(No1_1))
print(np.float64(No3_1))
print(np.float64(No5_1))

[440.   680.    15.5   15.5    0.33]
[232.         608.33333333  11.4         11.4          0.34333333]
[414.4   530.      8.06    8.06    0.496]


c:\Users\arads\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\arads\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\arads\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\arads\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\arads\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScal